config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/authorization'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :inca_receipts do
    collection do
      get :bill_download
    end
  end
  resources :inca_subscriptions do
    collection do
      get :bill_download
    end
  end
  resources :uvl_receipts do
    collection do
      get :bill_download
    end
  end
  resources :uvl_subscriptions do
    collection do
      get :bill_download
    end
  end
end

app/models/uvl_receipt.rb
# frozen_string_literal: true

class UvlReceipt < ActiveRecord::Base
  belongs_to :uvl_office
  belongs_to :payment_typology
  belongs_to :practise_typology
  belongs_to :lawyer
  belongs_to :category
  belongs_to :cancellation
  belongs_to :user
  belongs_to :subscription_verification

  before_create :set_name
  def set_name
    last_name = UvlReceipt.maximum(:name)
    self.name = last_name.to_i + 1
  end

  before_create :set_id
  def set_id
    last_id = UvlReceipt.maximum(:id)
    self.id = last_id.to_i + 1
  end

  has_attached_file :pdf
  validates_attachment_content_type :pdf, content_type: ['application/pdf']

  validates :date, presence: true
  validates :user_id, presence: true
  validates :institute, presence: true
  validates :uvl_office_id, presence: true
  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true, codice_fiscale_format: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :practise_typology_id, presence: true
  validates :company, presence: true
  validates :category_id, presence: true
  validates :cancellation_reason, if: -> { !cancellation_id.nil? }, presence: true
end

app/controllers/uvl_receipts_controller.rb
# frozen_string_literal: true

class UvlReceiptsController < ApplicationController
  before_action :set_uvl_receipt, only: %i[show edit update destroy]

  def index
    @user = current_user
    @q = UvlReceipt.ransack(params[:q])
    @uvl_receipts = @q.result(distinct: true).order(created_at: 'DESC').paginate(page: params[:page], per_page: 10)
  end

  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'uvl_receipts/pdfuvlreceipt', pdf: 'pdfuvlreceipt' }
    end
  end

  def bill_download
    @user = current_user
    @q = UvlReceipt.ransack(params[:q])
    @uvl_receipts = @q.result(distinct: true).order(created_at: 'ASC').where(cancellation_id: nil).paginate(page: params[:page], per_page: 50)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'uvl_receipts/pdfbilldownload', pdf: 'pdfbilldownload' }
    end
    @totale
    @totalegenerale
    @ufficio
    @contanti
    @contantitotale
    @pos
    @postotale
    @bonifico
    @bonificototale
    @ccpostale
    @ccpostaletotale
    @altro
    @altrototale
  end

  def new
    @uvl_receipt = UvlReceipt.new
    authorize! :create, @uvl_receipt
  end

  def edit
    authorize! :update, @uvl_receipt
  end

  def create
    @user = current_user
    @uvl_receipt = @user.uvl_receipts.build(uvl_receipt_params)
    @uvl_receipt.institute = @user.institute
    @uvl_receipt.date = Date.today
    respond_to do |format|
      if @uvl_receipt.save
        format.html { redirect_to @uvl_receipt, notice: 'Uvl receipt was successfully created.' }
        format.json { render :show, status: :created, location: @uvl_receipt }
      else
        format.html { render :new }
        format.json { render json: @uvl_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @uvl_receipt.update(uvl_receipt_params)
        format.html { redirect_to @uvl_receipt, notice: 'Uvl receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @uvl_receipt }
      else
        format.html { render :edit }
        format.json { render json: @uvl_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @uvl_receipt.destroy
    respond_to do |format|
      format.html { redirect_to uvl_receipts_url, notice: 'Uvl receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_uvl_receipt
    @uvl_receipt = UvlReceipt.find(params[:id])
  end

  def uvl_receipt_params
    params.require(:uvl_receipt).permit(:uvl_office_id, :customer_name, :customer_forname, :customer_birth_place, :customer_birth_date, :customer_fiscal_code, :customer_address, :customer_zip, :customer_city, :customer_province, :payment, :payment_typology_id, :practise_typology_id, :company, :lawyer_id, :category_id, :note, :cancellation_id, :cancellation_reason, :name, :date, :user_id, :institute, :subscription_verification_id, :pdf)
  end
end

app/helpers/uvl_receipts_helper.rb
module UvlReceiptsHelper
end

app/views/uvl_receipts/_cancellation_form.html.erb
<%= form_for(@uvl_receipt) do |f| %>
<% if @uvl_receipt.errors.any? %>
  <div id='error_explanation'>
    <h2>
      <%= pluralize(@uvl_receipt.errors.count, 'error') %>
      non posso salvare il record corrente:</h2>
    <ul>
      <% @uvl_receipt.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<strong>
  Ricevuta n°&nbsp;<%= @uvl_receipt.name %>&nbsp;del&nbsp;<%= @uvl_receipt.date.strftime('%d/%m/%Y') %>
  per:&nbsp;<%= @uvl_receipt.customer_name %>&nbsp;<%= @uvl_receipt.customer_forname %>&nbsp;-&nbsp;<%= @uvl_receipt.customer_fiscal_code %>
</strong>
<br>
<br>
<div class='row'>
  <div class='col col-lg-4'>
    <div class='field'>
      <%= f.label 'Annulla la Ricevuta::', id: 'text-primary' %><br>
      <%= f.collection_select(:cancellation_id, Cancellation.order('name ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
    </div>
    <br>
    <small>
      (* Il campo Motivo dell'Annullamento: &egrave; obbligatorio)
    </small>
    <div class='field'>
      <%= f.label 'Modivo dell\'Annullamento:', id: 'text-primary' %><br>
      <%= f.text_field :cancellation_reason, required: true, class: 'form-control' %>
    </div>
  </div>
</div>
<hr id='hr-grey'>
<div class='row'>
  <div class='col col-lg-4'>
    <div class='form-group'>
      <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm') do %>
      <%= fa_icon('save') %>&nbsp;Salva
    <% end %>
  </div>
</div>
</div>
<% end %>
<script type="text/javascript">
$('form').submit(function () { //When a form is submitted...
$('input').each(function () { //Check each input...
  if ($(this).val() == "") { //To see if it is empty...
    alert("Missing field"); //Say that it is
    return false; //Don't submit the form
  }
});
return; //If we made it this far, all is well, submit the form
});
</script>

app/views/uvl_receipts/_cancelled_form.html.erb
<div class='row'>
  <div class='col col-lg-6 col-lg-offset-3'>
    <div class='panel panel-danger'>
      <div class='panel panel-body'>
        <h3 id='text-centered'>
          <strong id='text-danger'>
            Annullata!
          </strong>
        </h3>
        <p id='text-centered'>
          Non puoi pi&ugrave; modificare la ricevuta corrente in quanto &egrave; stata annullata.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/uvl_receipts/bill_download.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_uvl.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Ufficio Vertenze e Legale&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('download') %>&nbsp;Scarico Ricevute:</strong>
    </h4>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-12'>
        <%= search_form_for @q, id: 'search-form', url: bill_download_uvl_receipts_path do |f| %>
        <div class='col col-lg-3'>
          <div class='field'>
            <%= f.label 'Data Inizio:' %><br>
            <%= f.text_field :date_gteq, class: 'datepicker form-control', id: 'datestart' %>
          </div>
          <div class='field'>
            <%= f.label 'Data Fine:' %><br>
            <%= f.text_field :date_lteq, class: 'datepicker form-control', id: 'dateend' %>
          </div>
        </div>
        <div class='col col-lg-4'>
          <div class="field">
            <%= f.label 'Ufficio:' %>
            <br>
            <%= f.collection_select(:uvl_office_id_eq, UvlOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control', :id => 'office-id'}) %>
          </div>
          <br>
          <div class='form-actions'>
            <%= button_tag type: 'submit', class: 'btn btn-default btn-sm' do %>
            <%= fa_icon('search') %>&nbsp;Cerca
          <% end %>
          <% if @uvl_receipts.count > 0 %>
            &nbsp;
            <%= link_to fa_icon('print') + ' ' + ' Stampa la Distinta', bill_download_uvl_receipts_path(request.parameters.merge(format: 'pdf')), target: 'new', class: 'btn btn-default btn-sm', id: 'print' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<hr id='hr-grey'>
<div class='row'>
  <div class='col col-lg-12'>
    <table class='table table-striped table-hove'>
      <thead>
        <tr>
          <th>Numero:</th>
          <th>Data:</th>
          <th>Nome e Cognome:</th>
          <th>Codice Fiscale:</th>
          <th>Ammontare:</th>
          <th>Note:</th>
        </tr>
      </thead>
      <tbody>
        <% @uvl_receipts.each do |uvl_receipt| %>
          <tr>
            <td><%= uvl_receipt.name %></td>
            <td><%= uvl_receipt.date.strftime('%d/%m/%Y') %></td>
            <td><%= uvl_receipt.customer_name %>&nbsp;<%= uvl_receipt.customer_forname %></td>
            <td><%= uvl_receipt.customer_fiscal_code %></td>
            <td><%= number_to_currency(uvl_receipt.payment) %></td>
            <td><%= uvl_receipt.note %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @uvl_receipts, :previous_label => t("precedente"), :next_label => t("prossimo"), renderer: BootstrapPagination::Rails %>
  </div>
</div>
</div>
</div>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({ language: 'it' });
  });

  $('#search-form').submit(function () {
    if ($('#office-id').val() == "") {
      alert("Devi selezionare l'Ufficio e cliccare su Cerca");
      return false;
    };
    if ($('#datestart').val() == "") {
      alert("Devi selezionare la data di Inizio");
      return false;
    };
    if ($('#dateend').val() == "") {
      alert("Devi selezionare la data di Fine");
      return false;
    };
    return;
  });

  $('#print').click(function () {
    if ($('#office-id').val() == "") {
      alert("Devi selezionare l'Ufficio e cliccare su Cerca");
      return false;
    };
    if ($('#datestart').val() == "") {
      alert("Devi selezionare la data di Inizio");
      return false;
    };
    if ($('#dateend').val() == "") {
      alert("Devi selezionare la data di Fine");
      return false;
    };
    return;
  });
</script>

app/views/uvl_receipts/edit.html.erb
<div class='panel panel-default'>
    <div class='panel-body'>
        <h4>
            <%= inline_svg('icon_uvl.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
            &nbsp;Ufficio Vertenze e Legale&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('pencil') %>&nbsp;Modifica Ricevuta:</strong>
            <span class='pull-right'>
                <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + '  ' + ' Ritorna all\'elenco', uvl_receipts_path, class: 'btn btn-default btn-sm' %>
            </span>
        </h4>
        <hr id='hr-grey'>
        <% if @uvl_receipt.cancellation_id != nil %>
          <%= render 'cancelled_form' %>
        <% else %>
          <%= render 'cancellation_form' %>
        <% end %>
    </div>
</div>

app/views/uvl_receipts/index.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_uvl.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Ufficio Vertenze e Legale&nbsp;<strong id='text-primary'>&nbsp;<%=  fa_icon('list') %>&nbsp;Elenco Ricevute:</strong>
    </h4>
    <hr id='hr-grey'>
      <table class='table table-striped table-hover'>
        <thead>
          <tr>
            <th></th>
            <th>Numero:</th>
            <th>Data:</th>
            <th>Nome:</th>
            <th>Codice Fiscale</th>
            <th>Ammontare</th>
            <th>Note:</th>
          </tr>
        </thead>
        <tbody>
          <% @uvl_receipts.each do |uvl_receipt| %>
          <tr>
            <td>
              <%= link_to fa_icon('pencil'), edit_uvl_receipt_path(uvl_receipt), id: 'text-warning' %>
            </td>
            <td>
              <% if uvl_receipt.cancellation_id == nil %>
                <%=link_to uvl_receipt.name, uvl_receipt, class: 'btn btn-default btn-xs' %>
              <% else %>
                <%=link_to uvl_receipt.name, uvl_receipt, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
            <td>
              <%= uvl_receipt.date.strftime('%d/%m/%Y') %>
            </td>
            <td>
              <%= uvl_receipt.customer_name %>&nbsp;<%= uvl_receipt.customer_forname %>
            </td>
            <td>
              <%= uvl_receipt.customer_fiscal_code %>
            </td>
            <td>
              <%= uvl_receipt.payment %>
            </td>
            <td>
              <%= truncate(uvl_receipt.note, length: 35) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= will_paginate @uvl_receipts, :previous_label => t("precedente"), :next_label => t("prossimo"), renderer: BootstrapPagination::Rails %>
  </div>
</div>
<div id='text-centered'>
  <h6>
    <small>
      <p id='notice'>
        <%= notice %>
      </p>
    </small>
  </h6>
</div>

app/views/uvl_receipts/new.html.erb
<div class='panel panel-default'>
    <div class='panel-body'>
        <h4>
            <%= inline_svg('icon_uvl.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
            &nbsp;Ufficio Vertenze e Legale&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('pencil') %>&nbsp;Nuova Ricevuta:</strong>
            <span class='pull-right'>
                <%= link_to fa_icon('arrow-left') + '  ' + ' Ritorna all\'elenco', uvl_receipts_path, class: 'btn btn-default btn-sm' %>
            </span>
        </h4>
        <hr id='hr-grey'>
        <%= render 'form' %>
    </div>
</div>

app/views/uvl_receipts/pdfuvlreceipt.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= stylesheet_link_tag wicked_pdf_asset_base64('pdfuvlreceipt') %>
  </head>
  <body>
    <div id='page'>
    <div id='header'>
      <div id='logo'>
          <%= inline_svg('header_ricevuta_uvl.svg', size: '170mm * 15mm', preserve_aspect_ratio: 'xMaxYMax meet') %>
      </div>
        <hr>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div>
        <div class='row'>
            <h3>
                <strong>
                  <%= @uvl_receipt.institute %>
                </strong>
                &nbsp;sede di:&nbsp;
                <strong>
                  <%= @uvl_receipt.uvl_office.name %>
                </strong>
            </h3>
            <p>
              <h3>
                RICEVUTA N°: <%= @uvl_receipt.name %>
                &nbsp;del&nbsp;
                <%= @uvl_receipt.date.strftime('%d/%m/%Y') %>
              </h3>
            </p>
            <p>
                <h3>
                  <strong>
                    <%= @uvl_receipt.practise_typology.name %>
                    &nbsp;
                    <%= @uvl_receipt.company %>
                  </strong>
                </h3>
            </p>
            <hr>
            <p>
              Si attesta che il Sig / la Sig.ra <strong><%= @uvl_receipt.customer_name %>&nbsp;<%= @uvl_receipt.customer_forname %></strong>
              C.F. <strong><%= @uvl_receipt.customer_fiscal_code %></strong> iscritto / a alla <strong><%= @uvl_receipt.category.name %></strong>
              ha versato un contributo per sostegno all'attivit&agrave;
              di assistenza di <strong><%= @uvl_receipt.institute %></strong> pari a <strong><%= number_to_currency(@uvl_receipt.payment) %></strong>
            </p>
            <br>
            <p>
                p.<%= @uvl_receipt.institute %><small>(<%= @uvl_receipt.uvl_office.name %>)</small>
                <br>
                <br>
                <br>
                <br>
                <br>
                ................................................................
                <br>
                <%= current_user.name %>
            </p>
            <br>
            <br>
            <p>
              L'attivit&agrave; svolta da <%= @uvl_receipt.institute %> rientra nelle finalit&agrave; statutarie della C.G.I.L.
              il versamento di contributi alle associazioni
              sindacali sono regolate dall'articolo 4 del D.P.R. n°633 del 26 ottobre 1972 e dall'articolo 111 D.P.R. n° 917
              e successive integrazioni
            </p>
            <p>
              <%= @uvl_receipt.subscription_verification.wording %>
            </p>
            <br>
        </div>
      </div>
    </div>
    <footer>
      <hr>
      <small>
        operatore:&nbsp;<%= current_user.name %>
        <br>
        <strong>OpisP1</strong> web-application to manage receipts and subscriptions - <strong>&copy;&nbsp;The Davosky Connection 2018</strong>
      </small>
    </footer>
    </div>
  </body>
</html>

app/views/uvl_receipts/show.html.erb
<% if @uvl_receipt.cancellation_id != nil %>
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_uvl.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato uvl&nbsp;
      <strong id='text-primary'>&nbsp;Ricevuta</strong>
      <span class='pull-right'>
        <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + ' ' + 'Ritorna alla Lista', uvl_receipts_path, class: 'btn btn-default btn-sm' %>
      </span>
    </h4>
    <hr id='hr-grey'>
    <br>
    <div class='panel panel-danger'>
      <div class='panel-body'>
        <h3 id='text-centered'>
          <strong id='text-danger'>
            Annullata!
          </strong>
        </h3>
        <p id='text-centered'>
          Non puoi visualizzare la ricevuta corrente in quanto &egrave; stata annullata.
          <br>
          ..................................................................................................
          <br>
          <small>
            Motivo Annullamento:
          </small>
          <br>
          <%= @uvl_receipt.cancellation_reason %>
        </p>
      </div>
    </div>
    <p id='text-centered'>
      <strong>
        Ricevuta n°&nbsp;
        <%= @uvl_receipt.name %>&nbsp;del&nbsp;
        <%= @uvl_receipt.created_at.strftime('%d/%m/%Y') %>
        &nbsp; creata ale ore:&nbsp;
        <%= @uvl_receipt.created_at.strftime('%H:%M') %>&nbsp;
        per:&nbsp;
        <%= @uvl_receipt.customer_name %>&nbsp;
        <%= @uvl_receipt.customer_forname %>
        &nbsp;C.F.&nbsp;
        <%= @uvl_receipt.customer_fiscal_code %>
      </strong>
    </p>
  </div>
</div>
<% else %>
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_uvl.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Ufficio Vertenze e Legale&nbsp;
      <strong id='text-primary'>
        &nbsp;Ricevuta:&nbsp;
        <%= @uvl_receipt.name %>&nbsp;del:&nbsp;
        <%= @uvl_receipt.date.strftime('%d/%m/%Y') %></strong>
      <span class='pull-right'>
        <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + ' ' + 'Ritorna alla Lista', uvl_receipts_path, class: 'btn btn-default btn-sm' %>
        <% if @uvl_receipt.pdf_file_name == nil %>
        &nbsp;
        <%= link_to fa_icon('print') + ' ' + ' Stampa la Ricevuta da firmare', uvl_receipt_path(@uvl_receipt, format: 'pdf'), target: 'new', class: 'btn btn-default btn-sm' %>
        <% end %>
      </span>
    </h4>
    <hr id='hr-grey'>
    <% if @uvl_receipt.pdf_file_name == nil %>
    <div class='row'>
      <div class='col col-lg-12'>
        <%= form_for(@uvl_receipt) do |f| %>
        <% if @uvl_receipt.errors.any? %>
        <div id='error_explanation'>
          <h2>
            <%= pluralize(@uvl_receipt.errors.count, 'error') %>
            non posso salvare il record corrente:</h2>
          <ul>
            <% @uvl_receipt.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class='field'>
          <div class='well well-lg'>
            <h4>
              <%= f.label 'Allega la Ricevuta firmata(pdf):' %><br>
              <%= f.file_field :pdf, class: 'btn btn-default btn-sm' %>
            </h4>
            <div class='row'>
              <div class='col col-lg-12'>
                <div class='col col-lg-4'>
                  <% if @uvl_receipt.payment >= 77.44 %>
                  <div class='alert alert-warning'>
                    <h4>ATTENZIONE!</h4>
                    <p>L'importo supera i 77,44 Euro ricordarsi di allegare la marca da bollo!</p>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class='form-group'>
          <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm') do %>
          <%= fa_icon('save') %>&nbsp;Salva
          <% end %>
        </div>
        <hr id='hr-grey'>
        <% end %>
        <% end %>
        <dl class='dl-horizontal'>
          <div class='row'>
            <div class='col col-lg-4'>
              <dt>Data:</dt>
              <dd>
                <%= @uvl_receipt.date.strftime('%d/%m/%Y') %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Operatore:</dt>
              <dd>
                <%= @uvl_receipt.user.name %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Istituto:</dt>
              <dd>
                <%= @uvl_receipt.institute %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Ufficio:</dt>
              <dd>
                <%= @uvl_receipt.uvl_office.name %>
                <br>
                <hr id='hr-grey'>
              </dd>
            </div>
            <div class='col col-lg-4'>
              <dt>Nome e Cognome:</dt>
              <dd>
                <%= @uvl_receipt.customer_name %>&nbsp;
                <%= @uvl_receipt.customer_forname %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Luogo di nascita:</dt>
              <dd>
                <%= @uvl_receipt.customer_birth_place %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Data di Nascita:</dt>
              <dd>
                <%= @uvl_receipt.customer_birth_date.strftime('%d/%m/%Y') %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Codice Fiscale:</dt>
              <dd>
                <%= @uvl_receipt.customer_fiscal_code %>
                <br>
                <hr id='hr-grey'>
              </dd>
            </div>
            <div class='col col-lg-4'>
              <dt>Indirizzo:</dt>
              <dd>
                <%= @uvl_receipt.customer_address %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Cap:</dt>
              <dd>
                <%= @uvl_receipt.customer_zip %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>Comune:</dt>
              <dd>
                <%= @uvl_receipt.customer_city %>
                <br>
                <hr id='hr-grey'>
              </dd>
              <dt>provincia:</dt>
              <dd>
                <%= @uvl_receipt.customer_province %>
                <br>
                <hr id='hr-grey'>
              </dd>
            </div>
          </div>
          <hr id='hr-grey'>
          <div class='row'>
            <div class='col col-lg-4'>
              <dt>Tipo Pagamento:</dt>
              <dd>
                <%= @uvl_receipt.payment_typology.name %>
              </dd>
              <dt>Ammontare:</dt>
              <dd>
                <strong>
                  <%= number_to_currency(@uvl_receipt.payment) %></strong>
              </dd>
            </div>
            <div class='col col-lg-8'>
              <dt>Note:</dt>
              <dd>
                <%= @uvl_receipt.note %>
              </dd>
            </div>
          </div>
        </dl>
      </div>
    </div>
    <div class='row'>
      <div class='col col-lg-12'>
        <div class='row'>
          <div class='col col-lg-12' id='text-centered'>
            <% if @uvl_receipt.pdf_file_name != nil %>
            <iframe src=<%=@uvl_receipt.pdf %> width='945' height='1340' style='border: none;'></iframe>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>