config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/authorization'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :inca_receipts do
    collection do
      get :bill_download
    end
  end
  resources :inca_subscriptions do
    collection do
      get :bill_download
    end
  end
  resources :uvl_receipts do
    collection do
      get :bill_download
    end
  end
  resources :uvl_subscriptions do
    collection do
      get :bill_download
    end
  end
end

app/models/inca_subscription.rb
class IncaSubscription < ActiveRecord::Base
  belongs_to :inca_office
  belongs_to :subscription_typology
  belongs_to :sex
  belongs_to :company_typology
  belongs_to :work_qualify
  belongs_to :work_level
  belongs_to :work_worker
  belongs_to :payment_typology
  belongs_to :category
  belongs_to :subscription_year
  belongs_to :inca_practise
  belongs_to :privacy_one
  belongs_to :privacy_two
  belongs_to :privacy_three
  belongs_to :cancellation
  belongs_to :user
  belongs_to :delivery_card

  before_create :set_name
  def set_name
    last_name = IncaSubscription.maximum(:name)
    self.name = last_name.to_i + 1
  end

  has_attached_file :pdf
  validates_attachment_content_type :pdf, :content_type => ['application/pdf']

  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true, codice_fiscale_format: true
  validates :sex_id, presence: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :customer_nationality, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :inca_office_id, presence: true
  validates :inca_practise_id, presence: true
  validates :subscription_year, presence: true
  validates :category_id, presence: true
  validates :privacy_one, presence: true
  validates :privacy_two, presence: true
  validates :privacy_three, presence: true
  validates :delivery_card_id, presence: true
  validates_presence_of :cancellation_reason, :if => lambda { self.cancellation_id != nil }
end

app/controllers/inca_subscriptions_controller.rb
class IncaSubscriptionsController < ApplicationController
  before_action :set_inca_subscription, only: %i[show edit update destroy]

  def index
    @tariffs = Tariff.all.order(position: 'ASC')
    @user = current_user
      @q = IncaSubscription.ransack(params[:q])
      @inca_subscriptions = @q.result(distinct: true)
                              .order(created_at: 'DESC')
                              .paginate(page: params[:page], per_page: 10)
  end

  def show;
    @tariffs = Tariff.all.order(position: 'ASC')
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'inca_subscriptions/pdfincasubscription', pdf: 'pdfincasubscription' }
    end
  end

  def bill_download
      @tariffs = Tariff.all.order(position: 'ASC')
      @q = IncaSubscription.ransack(params[:q])
      @inca_subscriptions = @q.result(distinct: true)
                              .order(created_at: 'DESC')
                              .where(cancellation_id: nil)
                              .paginate(page: params[:page], per_page: 50)
      respond_to do |format|
        format.html
        format.json
        format.pdf { render template: 'inca_subscriptions/pdfbilldownload', pdf: 'pdfbilldownload' }
      end
    @totale
    @totalegenerale
    @ufficio
    @contanti
    @contantitotale
    @pos
    @postotale
    @bonifico
    @bonificototale
    @ccpostale
    @ccpostaletotale
    @altro
    @altrototale
  end

  def new
    @inca_subscription = IncaSubscription.new
    @tariffs = Tariff.all.order(position: 'ASC')
    authorize! :create, @inca_subscription
  end

  def edit;
    @tariffs = Tariff.all.order(position: 'ASC')
    authorize! :update, @inca_subscription
  end

  def create
    @tariffs = Tariff.all.order(position: 'ASC')
    @user = current_user

    @inca_subscription = @user.inca_subscriptions.build(inca_subscription_params)

    @inca_subscription.institute = @user.institute
    @inca_subscription.date = Date.today

    respond_to do |format|
      if @inca_subscription.save
        format.html { redirect_to @inca_subscription, notice: 'Inca subscription was successfully created.' }
        format.json { render :show, status: :created, location: @inca_subscription }
      else
        format.html { render :new }
        format.json { render json: @inca_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tariffs = Tariff.all.order(position: 'ASC')
    respond_to do |format|
      if @inca_subscription.update(inca_subscription_params)
        format.html { redirect_to @inca_subscription, notice: 'Inca subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @inca_subscription }
      else
        format.html { render :edit }
        format.json { render json: @inca_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tariffs = Tariff.all.order(position: 'ASC')
    @inca_subscription.destroy
    respond_to do |format|
      format.html { redirect_to inca_subscriptions_url, notice: 'Inca subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_inca_subscription
    @inca_subscription = IncaSubscription.find(params[:id])
  end

  def inca_subscription_params
    params.require(:inca_subscription).permit(:inca_office_id, :subscription_typology_id, :customer_name, :customer_forname, :sex_id, :customer_birth_place, :customer_birth_date, :customer_fiscal_code, :customer_nationality, :customer_address, :customer_zip, :customer_city, :customer_province, :customer_phone, :customer_mobile, :customer_email, :company_name, :company_address, :company_zip, :company_city, :company_province, :company_typology_id, :work_qualify_id, :work_level_id, :work_contract, :work_worker_id, :work_employee_date, :work_workplace, :payment, :payment_typology_id, :category_id, :subscription_year_id, :inca_practise_id, :privacy_one_id, :privacy_two_id, :privacy_three_id, :note, :cancellation_id, :cancellation_reason, :name, :date, :user_id, :institute, :pdf, :card_delivery, :delivery_card_id)
  end
end

app/helpers/inca_subscriptions_helper.rb
module IncaSubscriptionsHelper
end

app/views/inca_subscriptions/bill_download.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
        <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
        &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('download') %>&nbsp;Scarico Sottoscrizioni:</strong>
    </h4>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-12'>
        <%= search_form_for @q, id: 'search-form', url: bill_download_inca_subscriptions_path do |f| %>
        <div class='col col-lg-3'>
          <div class='field'>
            <%= f.label 'Data Inizio:' %><br>
            <%= f.text_field :date_gteq, class: 'datepicker form-control', id: 'datestart' %>
          </div>
          <div class='field'>
            <%= f.label 'Data Fine:' %><br>
            <%= f.text_field :date_lteq, class: 'datepicker form-control', id: 'dateend' %>
          </div>
        </div>
        <div class='col col-lg-4'>
          <div class='field'>
            <%= f.label 'Ufficio:' %>
            <br>
            <%= f.collection_select(:inca_office_id_eq, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control', :id => 'office-id'}) %>
          </div>
          <div class='field'>
            <%= f.label 'Categoria:' %>
            <br>
            <%= f.collection_select(:category_id_eq, Category.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control', :id => 'office-id'}) %>
          </div>
          <br>
          <div class='form-actions'>
            <%= button_tag type: 'submit', class: 'btn btn-default btn-sm' do %>
            <%= fa_icon('search') %>&nbsp;Cerca
          <% end %>
          <% if @inca_subscriptions.count > 0 %>
            &nbsp;
            <%= link_to fa_icon('print') + ' ' + ' Stampa la Distinta', bill_download_inca_subscriptions_path(request.parameters.merge(format: 'pdf')), target: 'new', class: 'btn btn-default btn-sm', id: 'print' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<hr id='hr-grey'>
<div class='row'>
  <div class='col col-lg-12'>
    <table class='table table-striped table-hove'>
      <thead>
        <tr>
          <th>Numero:</th>
          <th>Data:</th>
          <th>Nome e Cognome:</th>
          <th>Codice Fiscale:</th>
          <th>Categoria</th>
          <th>Ammontare:</th>
          <th>Note:</th>
        </tr>
      </thead>
      <tbody>
        <% @inca_subscriptions.each do |inca_subscription| %>
          <tr>
            <td><%= inca_subscription.name %></td>
            <td><%= inca_subscription.date.strftime('%d/%m/%Y') %></td>
            <td><%= inca_subscription.customer_name %>&nbsp;<%= inca_subscription.customer_forname %></td>
            <td><%= inca_subscription.customer_fiscal_code %></td>
            <td><%= inca_subscription.category.name %></td>
            <td><%= number_to_currency(inca_subscription.payment) %></td>
            <td><%= inca_subscription.note %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @inca_subscriptions, :previous_label => t("precedente"), :next_label => t("prossimo"), renderer: BootstrapPagination::Rails %>
  </div>
</div>
</div>
</div>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({ language: 'it' });
  });

  $('#search-form').submit(function () {
    if ($('#office-id').val() == "") {
      alert("Devi selezionare l'Ufficio e cliccare su Cerca");
      return false;
    };
    if ($('#datestart').val() == "") {
      alert("Devi selezionare la data di Inizio");
      return false;
    };
    if ($('#dateend').val() == "") {
      alert("Devi selezionare la data di Fine");
      return false;
    };
    return;
  });

  $('#print').click(function () {
    if ($('#office-id').val() == "") {
      alert("Devi selezionare l'Ufficio e cliccare su Cerca");
      return false;
    };
    if ($('#datestart').val() == "") {
      alert("Devi selezionare la data di Inizio");
      return false;
    };
    if ($('#dateend').val() == "") {
      alert("Devi selezionare la data di Fine");
      return false;
    };
    return;
  });
</script>

app/views/inca_subscriptions/edit.html.erb
<div class='panel panel-default'>
    <div class='panel-body'>
        <h4>
            <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
            &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;
                <%= fa_icon('pencil') %>&nbsp;Modifica Sottoscrizione:</strong>
            <span class='pull-right'>
                <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + '  ' + ' Ritorna all\'elenco', inca_subscriptions_path, class: 'btn btn-default btn-sm' %>
            </span>
        </h4>
        <hr id='hr-grey'>
        <% if @inca_subscription.cancellation_id != nil %>
        <%= render 'cancelled_form' %>
        <% else %>
        <%= render 'cancellation_form' %>
        <% end %>
    </div>
</div>

app/views/inca_subscriptions/index.html.erb
<div class='panel panel-default'>
    <div class='panel-body'>
      <h4>
        <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
        &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;<%=  fa_icon('list') %>&nbsp;Elenco Sottoscrizioni:</strong>
      </h4>
      <hr id='hr-grey'>
        <table class='table table-striped table-hover'>
          <thead>
            <tr>
              <th></th>
              <th>Numero:</th>
              <th>Data:</th>
              <th>Nome:</th>
              <th>Codice Fiscale</th>
              <th>Categoria:</th>
              <th>Ammontare</th>
              <th>Note:</th>
            </tr>
          </thead>
          <tbody>
            <% @inca_subscriptions.each do |inca_subscription| %>
            <tr>
              <td>
                <%= link_to fa_icon('pencil'), edit_inca_subscription_path(inca_subscription), id: 'text-warning' %>
              </td>
              <td>
                <% if inca_subscription.cancellation_id == nil %>
                  <%=link_to inca_subscription.name, inca_subscription, class: 'btn btn-default btn-xs' %>
                <% else %>
                  <%=link_to inca_subscription.name, inca_subscription, class: 'btn btn-danger btn-xs' %>
                <% end %>
              </td>
              <td>
                <%= inca_subscription.date.strftime('%d/%m/%Y') %>
              </td>
              <td>
                <%= inca_subscription.customer_name %>&nbsp;<%= inca_subscription.customer_forname %>
              </td>
              <td>
                <%= inca_subscription.customer_fiscal_code %>
              </td>
              <td>
                  <%= inca_subscription.category.name %>
              </td>
              <td>
                <%= number_to_currency(inca_subscription.payment) %>
              </td>
              <td>
                <%= truncate(inca_subscription.note, length: 35) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <br>
        <%= will_paginate @inca_subscriptions, :previous_label => t("precedente"), :next_label => t("prossimo"), renderer: BootstrapPagination::Rails %>
    </div>
  </div>
  <div id='text-centered'>
    <h6>
      <small>
        <p id='notice'>
          <%= notice %>
        </p>
      </small>
    </h6>
  </div>
  

app/views/inca_subscriptions/show.html.erb
<% if @inca_subscription.cancellation_id != nil %>
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato INCA&nbsp;
      <strong id='text-primary'>&nbsp;Sottoscrizione</strong>
      <span class='pull-right'>
        <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + ' ' + 'Ritorna alla Lista', inca_subscriptions_path, class: 'btn btn-default btn-sm' %>
      </span>
    </h4>
    <hr id='hr-grey'>
    <br>
    <div class='panel panel-danger'>
      <div class='panel-body'>
        <h3 id='text-centered'>
          <strong id='text-danger'>
            Annullata!
          </strong>
        </h3>
        <p id='text-centered'>
          Non puoi visualizzare la ricevuta corrente in quanto &egrave; stata annullata.
          <br>
          ..................................................................................................
          <br>
          <small>
            Motivo Annullamento:
          </small>
          <br>
          <%= @inca_subscription.cancellation_reason %>
        </p>
      </div>
    </div>
    <p id='text-centered'>
      <strong>
        Sottoscrizione n°&nbsp;
        <%= @inca_subscription.name %>&nbsp;del&nbsp;
        <%= @inca_subscription.created_at.strftime('%d/%m/%Y') %>
        &nbsp; creata ale ore:&nbsp;
        <%= @inca_subscription.created_at.strftime('%H:%M') %>&nbsp;
        per:&nbsp;
        <%= @inca_subscription.customer_name %>&nbsp;
        <%= @inca_subscription.customer_forname %>
        &nbsp;C.F.&nbsp;
        <%= @inca_subscription.customer_fiscal_code %>
      </strong>
    </p>
  </div>
</div>
<% else %>
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato INCA&nbsp;
      <strong id='text-primary'>
        &nbsp;Sottoscrizione:&nbsp;
        <%= @inca_subscription.name %>&nbsp;del:&nbsp;
        <%= @inca_subscription.date.strftime('%d/%m/%Y') %></strong>
      <span class='pull-right'>
        <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + ' ' + 'Ritorna alla Lista', inca_subscriptions_path, class: 'btn btn-default btn-sm' %>
        <% if @inca_subscription.pdf_file_name == nil %>
        &nbsp;
        <%= link_to fa_icon('print') + ' ' + ' Stampa la Sottoscrizione da firmare', inca_subscription_path(@inca_subscription, format: 'pdf'), target: 'new', class: 'btn btn-default btn-sm' %>
        <% end %>
      </span>
    </h4>
    <div class="row">
      <div class="col col-lg-6">
        <%= form_for(@inca_subscription) do |f| %>
        <% if @inca_subscription.errors.any? %>
        <hr id='hr-grey'>
        <div id='error_explanation'>
          <h2>
            <%= pluralize(@inca_subscription.errors.count, 'error') %>
            non posso salvare il record corrente:</h2>
          <ul>
            <% @inca_subscription.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <% if @inca_subscription.pdf_file_name == nil %>
        <div class='row'>
          <div class='col col-lg-12'>
            <div class='field'>
              <div class="well well-lg">
                <h4>
                  <%= f.label 'Allega la Ricevuta firmata(pdf):' %><br>
                  <%= f.file_field :pdf, class: 'btn btn-default btn-sm' %>
                  &nbsp;
                  <div class='form-group'>
                    <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm') do %>
                    <%= fa_icon('save') %>&nbsp;Salva
                    <% end %>
                </h4>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <% end%>
      </div>
    </div>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-6' id='text-centered'>
        <% if @inca_subscription.subscription_typology_id == 1 %>
        RINNOVO:&nbsp;
        <%= inline_svg('check_no.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        NUOVA ISCRIZIONE:&nbsp;
        <%= inline_svg('check_yes.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% elsif @inca_subscription.subscription_typology_id == 2 %>
        RINNOVO:&nbsp;
        <%= inline_svg('check_yes.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        NUOVA ISCRIZIONE:&nbsp;
        <%= inline_svg('check_no.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% end %>
      </div>
      <div class='col col-lg-6' id='text-centered'>
      <% if @inca_subscription.delivery_card_id != nil %>
        <% if @inca_subscription.delivery_card.name == 'SI' %>
        Tessera Consegnata:&nbsp;
        NO&nbsp;<%= inline_svg('check_no.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        SI:&nbsp;<%= inline_svg('check_yes.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% elsif @inca_subscription.delivery_card.name == 'NO' %>
        Tessera Consegnata:&nbsp;
        NO&nbsp;<%= inline_svg('check_yes.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        SI:&nbsp;<%= inline_svg('check_no.svg', size: '16pt * 16pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% end %>
      <% end %>
      </div>
    </div>
    <hr id='hr-grey'>

    <div class='row'>
      <div class='col col-lg-6'>
        <dl class='dl-horizontal'>
          <dt>Nome:</dt>
          <dd>
            <%= @inca_subscription.customer_name %>
          </dd>
          <dt>Cognome:</dt>
          <dd>
            <%= @inca_subscription.customer_forname %>
          </dd>
          <dt>Sesso:</dt>
          <dd>
            <%= @inca_subscription.sex.name %>
          </dd>
          <dt>Nato a:</dt>
          <dd>
            <%= @inca_subscription.customer_birth_place %>
          </dd>
          <dt>Nato il:</dt>
          <dd>
            <%= @inca_subscription.customer_birth_date.strftime('%d/%m/%Y') %>
          </dd>
          <dt>Nazionalit&agrave;</dt>
          <dd>
            <%= @inca_subscription.customer_nationality %>
          </dd>
        </dl>
      </div>
      <div class='col col-lg-6'>
        <dl class='dl-horizontal'>
          <dt>Indirizzo:</dt>
          <dd>
            <%= @inca_subscription.customer_address %>
          </dd>
          <dt>Cap:</dt>
          <dd>
            <%= @inca_subscription.customer_zip %>
          </dd>
          <dt>Comune:</dt>
          <dd>
            <%= @inca_subscription.customer_city %>
          </dd>
          <dt>Provincia:</dt>
          <dd>
            <%= @inca_subscription.customer_province %>
          </dd>
        </dl>
      </div>
    </div>
    <div class="row">
      <div class="col col-lg-6">
        <dl class='dl-horizontal'>
          <dt>Telefono:</dt>
          <dd>
            <%= @inca_subscription.customer_phone %>
          </dd>
          <dt>Cellulare:</dt>
          <dd>
            <%= @inca_subscription.customer_mobile %>
          </dd>
        </dl>
      </div>
      <div class="col col-lg-6">
        <dl class='dl-horizontal'>
          <dt>
            <h4>
              <strong>
                Codice Fiscale:
              </strong>
            </h4>
          </dt>
          <dd>
            <h4><strong id='text-info'>
                <%= @inca_subscription.customer_fiscal_code %></strong></h4>
          </dd>
        </dl>
      </div>
    </div>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-6'>
        <dl class='dl-horizontal'>
          <dt>Azienda:</dt>
          <dd>
            <%= @inca_subscription.company_name %>
          </dd>
          <dt>Tipologia:</dt>
          <% if @inca_subscription.company_typology_id != nil %>
          <dd>
            <%= @inca_subscription.company_typology.name %>
          </dd>
          <% else %>
          <dd></dd>
          <% end %>
          <dt>Indirizzo:</dt>
          <dd>
            <%= @inca_subscription.company_address %>
          </dd>
          <dt>Cap:</dt>
          <dd>
            <%= @inca_subscription.company_zip %>
          </dd>
          <dt>Comune:</dt>
          <dd>
            <%= @inca_subscription.company_city %>
          </dd>
          <dt>Provincia:</dt>
          <dd>
            <%= @inca_subscription.company_province %>
          </dd>
        </dl>
      </div>
      <div class='col col-lg-6'>
        <dl class='dl-horizontal'>
          <dt>Tipo lavoro:</dt>
          <% if @inca_subscription.work_worker_id != nil %>
          <dd>
            <%= @inca_subscription.work_worker.name %>
          </dd>
          <% else %>
          <dd></dd>
          <% end %>
          <dt>Qalifica:</dt>
          <% if @inca_subscription.work_qualify_id != nil %>
          <dd>
            <%= @inca_subscription.work_qualify.name %>
          </dd>
          <% else %>
          <dd></dd>
          <% end %>
          <dt>Livello:</dt>
          <% if @inca_subscription.work_level_id != nil %>
          <dd>
            <%= @inca_subscription.work_level.name %>
          </dd>
          <% else %>
          <dd></dd>
          <% end %>
          <dt>Contratto:</dt>
          <dd>
            <%= @inca_subscription.work_contract %>
          </dd>
          <dt>Data Assunzione:</dt>
          <% if @inca_subscription.work_employee_date != nil %>
          <dd>
            <%= @inca_subscription.work_employee_date.strftime('%d/%m/%Y') %>
          </dd>
          <% else %>
          <dd></dd>
          <% end %>
          <dt>Sede Lavorativa:</dt>
          <dd>
            <%= @inca_subscription.work_workplace %>
          </dd>
        </dl>
      </div>
    </div>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-4' id='text-centered'>
        Ha versato: <strong>
          <%= number_to_currency(@inca_subscription.payment) %></strong>
      </div>
      <div class='col col-lg-4' id='text-centered'>
        per l'iscrizione alla categoria: <strong id='text-info'>
          <%= @inca_subscription.category.name %></strong>
      </div>
      <div class='col col-lg-4' id='text-centered'>
        in data: <strong id='text-info'>
          <%= @inca_subscription.date.strftime('%d/%m/%Y') %></strong>
      </div>
    </div>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-12'>
        <br>
        Sottoscrizione raccolta da:&nbsp;<strong>
          <%= @inca_subscription.institute %></strong>
        &nbsp;ufficio di:&nbsp;<strong>
          <%= @inca_subscription.inca_office.name %></strong>
        <br>
        &nbsp;operatore:&nbsp;<strong>
          <%= @inca_subscription.user.name %></strong>
        &nbsp;evento attivazione:&nbsp;<strong>
          <%= @inca_subscription.inca_practise.name %></strong>
        <br>
        <br>
      </div>
    </div>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-12' id='text-centered'>
        Privacy 1:&nbsp;
        <% if @inca_subscription.privacy_one_id == 1 %>
        &nbsp;
        <%= inline_svg('check_yes.svg', size: '11pt * 11pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% else %>
        &nbsp;
        <%= inline_svg('check_no.svg', size: '11pt * 11pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% end %>
        &nbsp;
        Privacy 2:&nbsp;
        <% if @inca_subscription.privacy_two_id == 1 %>
        &nbsp;
        <%= inline_svg('check_yes.svg', size: '11pt * 11pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% else %>
        &nbsp;
        <%= inline_svg('check_no.svg', size: '11pt * 11pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% end %>
        &nbsp;
        Privacy 3:&nbsp;
        <% if @inca_subscription.privacy_three_id == 1 %>
        &nbsp;
        <%= inline_svg('check_yes.svg', size: '11pt * 11pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% else %>
        &nbsp;
        <%= inline_svg('check_no.svg', size: '11pt * 11pt', preserve_aspect_ratio: 'xMaxYMax meet') %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class='row'>
    <div class='col col-lg-12'>
      <div class='row'>
        <div class='col col-lg-12' id='text-centered'>
          <% if @inca_subscription.pdf_file_name != nil %>
          <iframe src=<%=@inca_subscription.pdf %> width='945' height='1340' style='border: none;'></iframe>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>