config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/authorization'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :inca_receipts do
    collection do
      get :bill_download
    end
  end
  resources :inca_subscriptions do
    collection do
      get :bill_download
    end
  end
  resources :uvl_receipts do
    collection do
      get :bill_download
    end
  end
  resources :uvl_subscriptions do
    collection do
      get :bill_download
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      if user.admin == true
        can :manage, :all
      else
        if user.institute == 'Patronato INCA'
          can :read, IncaReceipt
          can :create, IncaReceipt
          can :update, IncaReceipt do |inca_receipt|
            inca_receipt.user == user
          end
          can :read, IncaSubscription
          can :create, IncaSubscription
          can :update, IncaSubscription do |inca_subscription|
            inca_subscription.user == user
          end
        end
        if user.institute == 'Ufficio Vertenze e Legale'
          can :read, UvlReceipt
          can :create, UvlReceipt
          can :update, UvlReceipt do |uvl_receipt|
            uvl_receipt.user == user
          end
          can :read, UvlSubscription
          can :create, UvlSubscription
          can :update, UvlSubscription do |uvl_subscription|
            uvl_subscription.user == user
          end
        end
      end
    end
  end
end

app/models/cancellation.rb
class Cancellation < ActiveRecord::Base
    has_many :inca_receipts
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    has_many :uvl_receipts
    validates :name, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :uvl_receipts
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    has_many :tariffs
    validates :name, presence: true
    validates :position, presence: true
end

app/models/delivery_card.rb
class DeliveryCard < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
end

app/models/inca_office.rb
class IncaOffice < ActiveRecord::Base
    has_many :inca_receipts
    has_many :inca_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/inca_practise.rb
class IncaPractise < ActiveRecord::Base
    has_many :inca_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/inca_receipt.rb
class IncaReceipt < ActiveRecord::Base
  belongs_to :inca_office
  belongs_to :payment_typology
  belongs_to :cancellation
  belongs_to :user

  before_create :set_name
  def set_name
    last_name = IncaReceipt.maximum(:name)
    self.name = last_name.to_i + 1
  end

  has_attached_file :pdf
  validates_attachment_content_type :pdf, :content_type => ['application/pdf']

  validates :date, presence: true
  validates :user_id, presence: true
  validates :institute, presence: true
  validates :inca_office_id, presence: true
  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true, codice_fiscale_format: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :cancellation_reason, :if => lambda { self.cancellation_id != nil }, presence: true
end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base
    has_many :uvl_receipts
    validates :name, presence: true
    validates :position, presence: true
end

app/models/privacy_one.rb
class PrivacyOne < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/privacy_three.rb
class PrivacyThree < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/privacy_two.rb
class PrivacyTwo < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/sex.rb
class Sex < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/tariff.rb
class Tariff < ActiveRecord::Base
  belongs_to :category

  before_create :set_name
  def set_name
    last_name = Tariff.maximum(:name)
    self.name = last_name.to_i + 1
  end

  validates :category_id, presence: true
  validates :typology, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable, :rememberable, :validatable, :registerable
  devise :database_authenticatable

  has_many :inca_receipts
  has_many :inca_subscriptions
  has_many :uvl_receipts
  has_many :uvl_subscriptions

  validates :name, presence: true
  validates :institute, presence: true
end

app/models/uvl_office.rb
class UvlOffice < ActiveRecord::Base
    has_many :uvl_receipts
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/uvl_receipt.rb
# frozen_string_literal: true

class UvlReceipt < ActiveRecord::Base
  belongs_to :uvl_office
  belongs_to :payment_typology
  belongs_to :practise_typology
  belongs_to :lawyer
  belongs_to :category
  belongs_to :cancellation
  belongs_to :user
  belongs_to :subscription_verification

  before_create :set_name
  def set_name
    last_name = UvlReceipt.maximum(:name)
    self.name = last_name.to_i + 1
  end

  before_create :set_id
  def set_id
    last_id = UvlReceipt.maximum(:id)
    self.id = last_id.to_i + 1
  end

  has_attached_file :pdf
  validates_attachment_content_type :pdf, content_type: ['application/pdf']

  validates :date, presence: true
  validates :user_id, presence: true
  validates :institute, presence: true
  validates :uvl_office_id, presence: true
  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true, codice_fiscale_format: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :practise_typology_id, presence: true
  validates :company, presence: true
  validates :category_id, presence: true
  validates :cancellation_reason, if: -> { !cancellation_id.nil? }, presence: true
end

app/models/work_level.rb
class WorkLevel < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/work_qualify.rb
class WorkQualify < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/models/work_worker.rb
class WorkWorker < ActiveRecord::Base
    has_many :inca_subscriptions
    has_many :uvl_subscriptions
    validates :name, presence: true
    validates :position, presence: true
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpisP1</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user %>
      <div class='container'>
        <div class="row">
          <div class="col col-lg-12">
            <%= render 'shared/navbar' %>
          </div>
        </div>
        <div class='row'>
          <div class='col col-lg-2'>
            <%= render 'shared/sidebar' %>
          </div>
          <div class='col col-lg-10'>
            <%= yield %>
            <br>
            <footer id='text-centered'>
              <br>
              <hr>
              <br>
              <p class="notice">
                <h6>
                  <small>
                    <%= notice %>
                  </small>
                </h6>
              </p>
              <p class="alert">
                <h6>
                  <small>
                    <%= alert %>
                  </small>
                </h6>
              </p>
            </footer>
          </div>
        </div>
      </div>
    <% else %>
      <div class='container'>
        <div class='row'>
          <div class='col col-lg-4 col-lg-offset-4'>
            <br>
            <br>
            <br>
            <%= yield %>
          </div>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li>
          <a href='#'>
            <small>
              <strong>
                <%= fa_icon('calendar') %>&nbsp;&nbsp;
                <%= l(Date.today, format: '%A %d %B %Y') %>
              </strong>
            </small>
          </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
            <strong>
              <%= fa_icon('user') %>&nbsp;&nbsp;
              <%= current_user.name %>&nbsp;&nbsp;|&nbsp;&nbsp;<small>
              <%= current_user.institute %></small>
              <span class='caret'></span></a>
          </strong>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <% if current_user %>
              <% if current_user.admin == true %>
              <%= link_to  fa_icon('cog') + ' ' + ' AMMINISTRAZIONE', rails_admin_path %>
              <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to fa_icon('info-circle') + ' ' + ' INFO', home_about_path %>
            </li>
            <li>
              <%= link_to fa_icon('user') + ' ' + ' ESCI', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<nav class='navbar-lite navbar-side' role='navigation'>
  <div class='container-fluid'>
    <div class='sidebar-collapse'>
      <ul class='nav' id='main-menu'>
        <li>
          <%= link_to inline_svg('sidebar_logo.svg', size: '128px * 72px', preserve_aspect_ratio: 'xMaxYMax meet'), root_path %>
        </li>
        <% if current_user.institute == 'Patronato INCA' || current_user.admin == true || current_user.manager == true %>
        <li>
          <hr id='hr-grey'>
        </li>
        <li>
          <h3>
            <%= inline_svg('icon_inca.svg', size: '28px * 28px', preserve_aspect_ratio: 'xMaxYMax meet')%>
            &nbsp;<strong id='text-info'>INCA</strong>
          </h3>
        </li>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false' id='condensed'>
            <%= fa_icon('file') %><br>
            <strong>RICEVUTE</strong>
          </a>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <%= link_to fa_icon('pencil') + ' ' + ' NUOVA RICEVUTA LIBERALITA\'', new_inca_receipt_path %>
            </li>
            <li>
              <%= link_to fa_icon('list') + ' ' + ' ELENCO RICEVUTE LIBERALITA\'', inca_receipts_path %>
            </li>
            <li>
              <%= link_to fa_icon('download') + ' ' + ' SCARICO RICEVUTE LIBERALITA\'', bill_download_inca_receipts_path %>
            </li>
          </ul>
        </li>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false' id='condensed'>
            <%= fa_icon('address-card') %><br>
            <strong>SOTTOSCRIZIONI</strong </a> <ul class='dropdown-menu' role='menu'>
        <li>
          <%= link_to fa_icon('pencil') + ' ' + ' NUOVA SOTTOSCRIZIONE', new_inca_subscription_path %>
        </li>
        <li>
          <%= link_to fa_icon('list') + ' ' + ' ELENCO SOTTOSCRIZIONI', inca_subscriptions_path %>
        </li>
        <li>
          <%= link_to fa_icon('download') + ' ' + ' SCARICO SOTTOSCRIZIONI', bill_download_inca_subscriptions_path %>
        </li>
      </ul>
      </li>
      <% end %>
      <% if current_user.institute == 'Ufficio Vertenze e Legale' || current_user.admin == true || current_user.manager == true %>
      <li>
        <hr id='hr-grey'>
      </li>
      <li>
        <h3>
          <%= inline_svg('icon_uvl.svg', size: '28px * 28px', preserve_aspect_ratio: 'xMaxYMax meet')%>
          &nbsp;<strong id='text-info'>UVL</strong>
        </h3>
      </li>
      <li class='dropdown'>
        <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false' id='condensed'>
          <%= fa_icon('address-card') %><br>
          <strong>SOTTOSCRIZIONI</strong </a> <ul class='dropdown-menu' role='menu'>
      <li>
        <%= link_to fa_icon('pencil') + ' ' + ' NUOVA SOTTOSCRIZIONE', new_uvl_subscription_path %>
      </li>
      <li>
        <%= link_to fa_icon('list') + ' ' + ' ELENCO SOTTOSCRIZIONI', uvl_subscriptions_path %>
      </li>
      <li>
        <%= link_to fa_icon('download') + ' ' + ' SCARICO SOTTOSCRIZIONI', bill_download_uvl_subscriptions_path %>
      </li>
      </ul>
      </li>
      <% end %>
      <li>
        <hr id='hr-grey'>
      </li>
      </ul>
    </div>
  </div>
</nav>