config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/authorization'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :inca_receipts do
    collection do
      get :bill_download
    end
  end
  resources :inca_subscriptions do
    collection do
      get :bill_download
    end
  end
  resources :uvl_receipts do
    collection do
      get :bill_download
    end
  end
  resources :uvl_subscriptions do
    collection do
      get :bill_download
    end
  end
end

app/models/inca_receipt.rb
class IncaReceipt < ActiveRecord::Base
  belongs_to :inca_office
  belongs_to :payment_typology
  belongs_to :cancellation
  belongs_to :user

  before_create :set_name
  def set_name
    last_name = IncaReceipt.maximum(:name)
    self.name = last_name.to_i + 1
  end

  has_attached_file :pdf
  validates_attachment_content_type :pdf, :content_type => ['application/pdf']

  validates :date, presence: true
  validates :user_id, presence: true
  validates :institute, presence: true
  validates :inca_office_id, presence: true
  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true, codice_fiscale_format: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :cancellation_reason, :if => lambda { self.cancellation_id != nil }, presence: true
end

app/controllers/inca_receipts_controller.rb
class IncaReceiptsController < ApplicationController
  before_action :set_inca_receipt, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    @q = IncaReceipt.ransack(params[:q])
    @inca_receipts = @q.result(distinct: true).order(created_at: 'DESC').paginate(page: params[:page], per_page: 10)
  end

  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'inca_receipts/pdfincareceipt', pdf: 'pdfincareceipt' }
    end
  end

  def bill_download
    @user = current_user
      @q = IncaReceipt.ransack(params[:q])
      @inca_receipts = @q.result(distinct: true).order(created_at: 'ASC').where(cancellation_id: nil).paginate(page: params[:page], per_page: 50)
      respond_to do |format|
        format.html
        format.json
        format.pdf { render template: 'inca_receipts/pdfbilldownload', pdf: 'pdfbilldownload' }
      end
    @totale
    @totalegenerale
    @ufficio
    @contanti
    @contantitotale
    @pos
    @postotale
    @bonifico
    @bonificototale
    @ccpostale
    @ccpostaletotale
    @altro
    @altrototale
  end

  def new
    @inca_receipt = IncaReceipt.new
    authorize! :create, @inca_receipt
  end

  def edit
    authorize! :update, @inca_receipt
  end

  def create
    @user = current_user
    @inca_receipt = @user.inca_receipts.build(inca_receipt_params)
    @inca_receipt.institute = @user.institute
    @inca_receipt.date = Date.today
    respond_to do |format|
      if @inca_receipt.save
        format.html { redirect_to @inca_receipt, notice: 'Inca receipt was successfully created.' }
        format.json { render :show, status: :created, location: @inca_receipt }
      else
        format.html { render :new }
        format.json { render json: @inca_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inca_receipt.update(inca_receipt_params)
        format.html { redirect_to @inca_receipt, notice: 'Inca receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @inca_receipt }
      else
        format.html { render :edit }
        format.json { render json: @inca_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inca_receipt.destroy
    respond_to do |format|
      format.html { redirect_to inca_receipts_url, notice: 'Inca receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_inca_receipt
      @inca_receipt = IncaReceipt.find(params[:id])
    end

    def inca_receipt_params
      params.require(:inca_receipt).permit(:inca_office_id, :customer_name, :customer_forname, :customer_birth_place, :customer_birth_date, :customer_fiscal_code, :customer_address, :customer_zip, :customer_city, :customer_province, :payment, :payment_typology_id, :note, :cancellation_id, :cancellation_reason, :name, :date, :user_id, :institute, :pdf)
    end
end

app/helpers/inca_receipts_helper.rb
module IncaReceiptsHelper
end

app/views/inca_receipts/_cancellation_form.html.erb
<%= form_for(@inca_receipt) do |f| %>
<% if @inca_receipt.errors.any? %>
  <div id='error_explanation'>
    <h2>
      <%= pluralize(@inca_receipt.errors.count, 'error') %>
      non posso salvare il record corrente:</h2>
    <ul>
      <% @inca_receipt.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<strong>
  Ricevuta n°&nbsp;<%= @inca_receipt.name %>&nbsp;del&nbsp;<%= @inca_receipt.date.strftime('%d/%m/%Y') %>
  per:&nbsp;<%= @inca_receipt.customer_name %>&nbsp;<%= @inca_receipt.customer_forname %>&nbsp;-&nbsp;<%= @inca_receipt.customer_fiscal_code %>
</strong>
<br>
<br>
<div class='row'>
  <div class='col col-lg-4'>
    <div class='field'>
      <%= f.label 'Annulla la Ricevuta::', id: 'text-primary' %><br>
      <%= f.collection_select(:cancellation_id, Cancellation.order('name ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
    </div>
    <br>
    <small>
      (* Il campo Motivo dell'Annullamento: &egrave; obbligatorio)
    </small>
    <div class='field'>
      <%= f.label 'Modivo dell\'Annullamento:', id: 'text-primary' %><br>
      <%= f.text_field :cancellation_reason, required: true, class: 'form-control' %>
    </div>
  </div>
</div>
<hr id='hr-grey'>
<div class='row'>
  <div class='col col-lg-4'>
    <div class='form-group'>
      <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm') do %>
      <%= fa_icon('save') %>&nbsp;Salva
    <% end %>
  </div>
</div>
</div>
<% end %>
<script type="text/javascript">
$('form').submit(function () { //When a form is submitted...
$('input').each(function () { //Check each input...
  if ($(this).val() == "") { //To see if it is empty...
    alert("Missing field"); //Say that it is
    return false; //Don't submit the form
  }
});
return; //If we made it this far, all is well, submit the form
});
</script>

app/views/inca_receipts/_cancelled_form.html.erb
<div class='row'>
  <div class='col col-lg-6 col-lg-offset-3'>
    <div class='panel panel-danger'>
      <div class='panel panel-body'>
        <h3 id='text-centered'>
          <strong id='text-danger'>
            Annullata!
          </strong>
        </h3>
        <p id='text-centered'>
          Non puoi pi&ugrave; modificare la ricevuta corrente in quanto &egrave; stata annullata.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/inca_receipts/_form.html.erb
<%= form_for(@inca_receipt) do |f| %>
  <% if @inca_receipt.errors.any? %>
    <div id='error_explanation'>
      <h3 id='text-danger'>
        Ci sonno errori di imissione o campi obbligatori mancanti. <br>
        Non posso salvare la sottoscrizione corrente! <br>
        <small id='text-warning'>elenco degli errori:</small>
      </h3>
      <ul>
      <% @inca_receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class="alert alert-dismissible alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>ATTENZIONE </strong> Tutti i campi contraddistinti dall'asterisco * sono OBBLIGATORI!
    </div>
    <div class='col col-lg-4'>
      <div class='field'>
        <%= f.label 'Ufficio:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.collection_select(:inca_office_id, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
      <div class='field'>
        <%= f.label 'Nome:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_name, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Cognome:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_forname, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Luogo di Nascita:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_birth_place, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Data di Nascita' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_birth_date, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Codice Fiscale:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_fiscal_code, class: 'form-control' %>
      </div>
    </div>
    <div class='col col-lg-4'>
      <div class='field'>
        <%= f.label 'Indirizzo:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_address, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Cap:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_zip, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Comune:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_city, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Provincia:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :customer_province, class: 'form-control' %>
      </div>
    </div>
    <div class='col col-lg-4'>
      <div class='field'>
        <%= f.label 'Ammontare:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.text_field :payment, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label 'Tipologia Pagamento:' %>&nbsp;<strong id='text-danger'>*</strong><br>
        <%= f.collection_select(:payment_typology_id, PaymentTypology.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
      <div class='field'>
        <%= f.label 'Note:' %><br>
        <%= f.text_area :note %>
      </div>
    </div>
  </div>
  <hr id='hr-grey'>
  <div class='row'>
    <div class='col col-lg-4'>
      <div class='form-group'>
        <%= button_tag(type: 'submit', class: 'btn btn-primary btn-sm') do %>
        <%= fa_icon('save') %>&nbsp;Salva
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/inca_receipts/bill_download.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('download') %>&nbsp;Scarico Ricevute Liberalit&agrave:</strong>
    </h4>
    <hr id='hr-grey'>
    <div class='row'>
      <div class='col col-lg-12'>
        <%= search_form_for @q, id: 'search-form', url: bill_download_inca_receipts_path do |f| %>
        <div class='col col-lg-3'>
          <div class='field'>
            <%= f.label 'Data Inizio:' %><br>
            <%= f.text_field :date_gteq, class: 'datepicker form-control', id: 'datestart' %>
          </div>
          <div class='field'>
            <%= f.label 'Data Fine:' %><br>
            <%= f.text_field :date_lteq, class: 'datepicker form-control', id: 'dateend' %>
          </div>
        </div>
        <div class='col col-lg-4'>
          <div class='field'>
            <%= f.label 'Ufficio:' %>
            <br>
            <%= f.collection_select(:inca_office_id_eq, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control', :id => 'office-id'}) %>
          </div>
          <br>
          <div class='form-actions'>
            <%= button_tag type: 'submit', class: 'btn btn-default btn-sm' do %>
            <%= fa_icon('search') %>&nbsp;Cerca
          <% end %>
          <% if @inca_receipts.count > 0 %>
            &nbsp;
            <%= link_to fa_icon('print') + ' ' + ' Stampa la Distinta', bill_download_inca_receipts_path(request.parameters.merge(format: 'pdf')), target: 'new', class: 'btn btn-default btn-sm', id: 'print' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<hr id='hr-grey'>
<div class='row'>
  <div class='col col-lg-12'>
    <table class='table table-striped table-hove'>
      <thead>
        <tr>
          <th>Numero:</th>
          <th>Data:</th>
          <th>Nome e Cognome:</th>
          <th>Codice Fiscale:</th>
          <th>Ammontare:</th>
          <th>Note:</th>
        </tr>
      </thead>
      <tbody>
        <% @inca_receipts.each do |inca_receipt| %>
          <tr>
            <td><%= inca_receipt.name %></td>
            <td><%= inca_receipt.date.strftime('%d/%m/%Y') %></td>
            <td><%= inca_receipt.customer_name %>&nbsp;<%= inca_receipt.customer_forname %></td>
            <td><%= inca_receipt.customer_fiscal_code %></td>
            <td><%= number_to_currency(inca_receipt.payment) %></td>
            <td><%= inca_receipt.note %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @inca_receipts, :previous_label => t("precedente"), :next_label => t("prossimo"), renderer: BootstrapPagination::Rails %>
  </div>
</div>
</div>
</div>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({ language: 'it' });
  });

  $('#search-form').submit(function () {
    if ($('#office-id').val() == "") {
      alert("Devi selezionare l'Ufficio e cliccare su Cerca");
      return false;
    };
    if ($('#datestart').val() == "") {
      alert("Devi selezionare la data di Inizio");
      return false;
    };
    if ($('#dateend').val() == "") {
      alert("Devi selezionare la data di Fine");
      return false;
    };
    return;
  });

  $('#print').click(function () {
    if ($('#office-id').val() == "") {
      alert("Devi selezionare l'Ufficio e cliccare su Cerca");
      return false;
    };
    if ($('#datestart').val() == "") {
      alert("Devi selezionare la data di Inizio");
      return false;
    };
    if ($('#dateend').val() == "") {
      alert("Devi selezionare la data di Fine");
      return false;
    };
    return;
  });
</script>

app/views/inca_receipts/edit.html.erb
<div class='panel panel-default'>
    <div class='panel-body'>
        <h4>
            <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
            &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('pencil') %>&nbsp;Modifica Ricevuta Liberalit&agrave:</strong>
            <span class='pull-right'>
                <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + '  ' + ' Ritorna all\'elenco', inca_receipts_path, class: 'btn btn-default btn-sm' %>
            </span>
        </h4>
        <hr id='hr-grey'>
        <% if @inca_receipt.cancellation_id != nil %>
          <%= render 'cancelled_form' %>
        <% else %>
          <%= render 'cancellation_form' %>
        <% end %>
    </div>
</div>

app/views/inca_receipts/index.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;<%=  fa_icon('list') %>&nbsp;Elenco Ricevute Liberalit&agrave:</strong>
    </h4>
    <hr id='hr-grey'>
      <table class='table table-striped table-hover'>
        <thead>
          <tr>
            <th></th>
            <th>Numero:</th>
            <th>Data:</th>
            <th>Nome:</th>
            <th>Codice Fiscale</th>
            <th>Ammontare</th>
            <th>Note:</th>
          </tr>
        </thead>
        <tbody>
          <% @inca_receipts.each do |inca_receipt| %>
          <tr>
            <td>
              <%= link_to fa_icon('pencil'), edit_inca_receipt_path(inca_receipt), id: 'text-warning' %>
            </td>
            <td>
              <% if inca_receipt.cancellation_id == nil %>
                <%=link_to inca_receipt.name, inca_receipt, class: 'btn btn-default btn-xs' %>
              <% else %>
                <%=link_to inca_receipt.name, inca_receipt, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </td>
            <td>
              <%= inca_receipt.date.strftime('%d/%m/%Y') %>
            </td>
            <td>
              <%= inca_receipt.customer_name %>&nbsp;<%= inca_receipt.customer_forname %>
            </td>
            <td>
              <%= inca_receipt.customer_fiscal_code %>
            </td>
            <td>
              <%= inca_receipt.payment %>
            </td>
            <td>
              <%= truncate(inca_receipt.note, length: 35) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= will_paginate @inca_receipts, :previous_label => t("precedente"), :next_label => t("prossimo"), renderer: BootstrapPagination::Rails %>
  </div>
</div>
<div id='text-centered'>
  <h6>
    <small>
      <p id='notice'>
        <%= notice %>
      </p>
    </small>
  </h6>
</div>

app/views/inca_receipts/new.html.erb
<div class='panel panel-default'>
    <div class='panel-body'>
        <h4>
            <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
            &nbsp;Patronato INCA&nbsp;<strong id='text-primary'>&nbsp;<%= fa_icon('pencil') %>&nbsp;Nuova Ricevuta Liberalit&agrave:</strong>
            <span class='pull-right'>
                <%= link_to fa_icon('arrow-left') + '  ' + ' Ritorna all\'elenco', inca_receipts_path, class: 'btn btn-default btn-sm' %>
            </span>
        </h4>
        <hr id='hr-grey'>
        <%= render 'form' %>
    </div>
</div>

app/views/inca_receipts/show.html.erb
<% if @inca_receipt.cancellation_id != nil %>
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato INCA&nbsp;
      <strong id='text-primary'>&nbsp;Ricevuta Liberalit&agrave</strong>
      <span class='pull-right'>
        <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + ' ' + 'Ritorna alla Lista', inca_receipts_path, class: 'btn btn-default btn-sm' %>
      </span>
    </h4>
    <hr id='hr-grey'>
    <br>
    <div class='panel panel-danger'>
      <div class='panel-body'>
        <h3 id='text-centered'>
          <strong id='text-danger'>
            Annullata!
          </strong>
        </h3>
        <p id='text-centered'>
          Non puoi visualizzare la ricevuta corrente in quanto &egrave; stata annullata.
          <br>
          ..................................................................................................
          <br>
          <small>
            Motivo Annullamento:
          </small>
          <br>
          <%= @inca_receipt.cancellation_reason %>
        </p>
      </div>
    </div>
    <p id='text-centered'>
      <strong>
        Ricevuta n°&nbsp;
        <%= @inca_receipt.name %>&nbsp;del&nbsp;
        <%= @inca_receipt.created_at.strftime('%d/%m/%Y') %>
        &nbsp; creata ale ore:&nbsp;
        <%= @inca_receipt.created_at.strftime('%H:%M') %>&nbsp;
        per:&nbsp;
        <%= @inca_receipt.customer_name %>&nbsp;
        <%= @inca_receipt.customer_forname %>
        &nbsp;C.F.&nbsp;
        <%= @inca_receipt.customer_fiscal_code %>
      </strong>
    </p>
  </div>
</div>
<% else %>
<div class='panel panel-default'>
  <div class='panel-body'>
    <h4>
      <%= inline_svg('icon_inca.svg', size: '36px * 36px', preserve_aspect_ratio: 'xMaxYMax meet')%>
      &nbsp;Patronato INCA&nbsp;
      <strong id='text-primary'>
        &nbsp;Ricevuta Liberalit&agrave:&nbsp;
        <%= @inca_receipt.name %>&nbsp;del:&nbsp;
        <%= @inca_receipt.date.strftime('%d/%m/%Y') %></strong>
      <span class='pull-right'>
        <%= link_to fa_icon('arrow-left') + ' ' + fa_icon('list') + ' ' + 'Ritorna alla Lista', inca_receipts_path, class: 'btn btn-default btn-sm' %>
        <% if @inca_receipt.pdf_file_name == nil %>
        &nbsp;
        <%= link_to fa_icon('print') + ' ' + ' Stampa la Ricevuta da firmare', inca_receipt_path(@inca_receipt, format: 'pdf'), target: 'new', class: 'btn btn-default btn-sm' %>
        <% end %>
      </span>
    </h4>
    <hr id='hr-grey'>
    <% if @inca_receipt.pdf_file_name == nil %>
    <div class='row'>
      <div class='col col-lg-12'>
        <%= form_for(@inca_receipt) do |f| %>
        <% if @inca_receipt.errors.any? %>
        <div id='error_explanation'>
          <h2>
            <%= pluralize(@inca_receipt.errors.count, 'error') %>
            non posso salvare il record corrente:</h2>
          <ul>
            <% @inca_receipt.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class='field'>
          <div class='well well-lg'>
            <h4>
              <%= f.label 'Allega la Ricevuta firmata(pdf):' %><br>
              <%= f.file_field :pdf, class: 'btn btn-default btn-sm' %>
            </h4>
            <div class='row'>
              <div class='col col-lg-12'>
                <div class='col col-lg-4'>
                  <% if @inca_receipt.payment >= 77.44 %>
                  <div class='alert alert-warning'>
                    <h4>ATTENZIONE!</h4>
                    <p>L'importo supera i 77,44 Euro ricordarsi di allegare la marca da bollo!</p>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class='form-group'>
          <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm') do %>
          <%= fa_icon('save') %>&nbsp;Salva
          <% end %>
        </div>
        <% end %>
        <hr id='hr-grey'>
      </div>
    </div>
    <% end %>
    <dl class='dl-horizontal'>
      <div class='row'>
        <div class='col col-lg-4'>
          <dt>Data:</dt>
          <dd>
            <%= @inca_receipt.date.strftime('%d/%m/%Y') %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Operatore:</dt>
          <dd>
            <%= @inca_receipt.user.name %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Istituto:</dt>
          <dd>
            <%= @inca_receipt.institute %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Ufficio:</dt>
          <dd>
            <%= @inca_receipt.inca_office.name %>
          </dd>
        </div>
        <div class='col col-lg-4'>
          <dt>Nome e Cognome:</dt>
          <dd>
            <%= @inca_receipt.customer_name %>&nbsp;
            <%= @inca_receipt.customer_forname %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Luogo di nascita:</dt>
          <dd>
            <%= @inca_receipt.customer_birth_place %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Data di Nascita:</dt>
          <dd>
            <%= @inca_receipt.customer_birth_date.strftime('%d/%m/%Y') %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Codice Fiscale:</dt>
          <dd>
            <%= @inca_receipt.customer_fiscal_code %>
          </dd>
        </div>
        <div class='col col-lg-4'>
          <dt>Indirizzo:</dt>
          <dd>
            <%= @inca_receipt.customer_address %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Cap:</dt>
          <dd>
            <%= @inca_receipt.customer_zip %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>Comune:</dt>
          <dd>
            <%= @inca_receipt.customer_city %>
            <br>
            <hr id='hr-grey'>
          </dd>
          <dt>provincia:</dt>
          <dd>
            <%= @inca_receipt.customer_province %>
          </dd>
        </div>
      </div>
      <hr id='hr-grey'>
      <div class='row'>
        <div class='col col-lg-4'>
          <dt>Tipo Pagamento:</dt>
          <dd>
            <%= @inca_receipt.payment_typology.name %>
          </dd>
          <dt>Ammontare:</dt>
          <dd>
            <strong>
              <%= number_to_currency(@inca_receipt.payment) %></strong>
          </dd>
        </div>
        <div class='col col-lg-8'>
          <dt>Note:</dt>
          <dd>
            <%= @inca_receipt.note %>
          </dd>
        </div>
      </div>
    </dl>
  </div>
</div>
<div class='row'>
  <div class='col col-lg-12'>
    <div class='row'>
      <div class='col col-lg-12' id='text-centered'>
        <% if @inca_receipt.pdf_file_name != nil %>
        <iframe src=<%=@inca_receipt.pdf %> width='945' height='1340' style='border: none;'></iframe>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>